// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Create(arg1, arg2) {
  return window['go']['collection']['Collection']['Create'](arg1, arg2);
}

export function Delete(arg1, arg2) {
  return window['go']['collection']['Collection']['Delete'](arg1, arg2);
}

export function List(arg1, arg2, arg3) {
  return window['go']['collection']['Collection']['List'](arg1, arg2, arg3);
}

export function Read(arg1, arg2) {
  return window['go']['collection']['Collection']['Read'](arg1, arg2);
}

export function Update(arg1, arg2, arg3) {
  return window['go']['collection']['Collection']['Update'](arg1, arg2, arg3);
}
