// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {system} from '../models';

export function DownloadStatus():Promise<system.DownloadStatusResult>;

export function GetSettings():Promise<system.SettingsResult>;

export function GetVersion():Promise<system.VersionResult>;

export function Status():Promise<system.StatusResult>;

export function UpdateSettings(arg1:system.UpdateSettingsRequest):Promise<system.SettingsResult>;
