// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function DownloadStatus() {
  return window['go']['system']['System']['DownloadStatus']();
}

export function GetSettings() {
  return window['go']['system']['System']['GetSettings']();
}

export function GetVersion() {
  return window['go']['system']['System']['GetVersion']();
}

export function Status() {
  return window['go']['system']['System']['Status']();
}

export function UpdateSettings(arg1) {
  return window['go']['system']['System']['UpdateSettings'](arg1);
}
