// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Create(arg1, arg2, arg3) {
  return window['go']['deck']['Deck']['Create'](arg1, arg2, arg3);
}

export function Delete(arg1, arg2, arg3) {
  return window['go']['deck']['Deck']['Delete'](arg1, arg2, arg3);
}

export function List(arg1, arg2, arg3, arg4) {
  return window['go']['deck']['Deck']['List'](arg1, arg2, arg3, arg4);
}

export function ListAllUnique(arg1) {
  return window['go']['deck']['Deck']['ListAllUnique'](arg1);
}

export function Read(arg1, arg2, arg3) {
  return window['go']['deck']['Deck']['Read'](arg1, arg2, arg3);
}

export function Update(arg1, arg2, arg3, arg4) {
  return window['go']['deck']['Deck']['Update'](arg1, arg2, arg3, arg4);
}
