// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {catalog} from '../models';
import {collection} from '../models';

export function Create(arg1:string,arg2:catalog.WriteRequest):Promise<collection.Result>;

export function Delete(arg1:string,arg2:string):Promise<void>;

export function List(arg1:string,arg2:string,arg3:string):Promise<collection.ListResult>;

export function Read(arg1:string,arg2:string):Promise<collection.Result>;

export function Update(arg1:string,arg2:string,arg3:catalog.WriteRequest):Promise<collection.Result>;
