// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {catalog} from '../models';
import {game} from '../models';

export function Create(arg1:catalog.WriteRequest):Promise<game.Result>;

export function Delete(arg1:string):Promise<void>;

export function Duplicate(arg1:string,arg2:string):Promise<game.Result>;

export function List(arg1:string,arg2:string):Promise<game.ListResult>;

export function Read(arg1:string):Promise<game.Result>;

export function Update(arg1:string,arg2:catalog.WriteRequest):Promise<game.Result>;
