// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Create(arg1) {
  return window['go']['game']['Game']['Create'](arg1);
}

export function Delete(arg1) {
  return window['go']['game']['Game']['Delete'](arg1);
}

export function Duplicate(arg1, arg2) {
  return window['go']['game']['Game']['Duplicate'](arg1, arg2);
}

export function Export(arg1) {
  return window['go']['game']['Game']['Export'](arg1);
}

export function List(arg1, arg2) {
  return window['go']['game']['Game']['List'](arg1, arg2);
}

export function Read(arg1) {
  return window['go']['game']['Game']['Read'](arg1);
}

export function Update(arg1, arg2) {
  return window['go']['game']['Game']['Update'](arg1, arg2);
}
