// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Prepare(arg1) {
  return window['go']['replace']['Replace']['Prepare'](arg1);
}

export function Replace(arg1, arg2) {
  return window['go']['replace']['Replace']['Replace'](arg1, arg2);
}
