// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {replace} from '../models';

export function Prepare(arg1:Array<number>):Promise<replace.PrepareResult>;

export function Replace(arg1:Array<number>,arg2:Array<number>):Promise<replace.Result>;
