// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Collection(arg1, arg2, arg3, arg4) {
  return window['go']['search']['Search']['Collection'](arg1, arg2, arg3, arg4);
}

export function Game(arg1, arg2, arg3) {
  return window['go']['search']['Search']['Game'](arg1, arg2, arg3);
}

export function Root(arg1, arg2) {
  return window['go']['search']['Search']['Root'](arg1, arg2);
}
