// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {catalog} from '../models';
import {deck} from '../models';

export function Create(arg1:string,arg2:string,arg3:catalog.WriteRequest):Promise<deck.Result>;

export function Delete(arg1:string,arg2:string,arg3:string):Promise<void>;

export function List(arg1:string,arg2:string,arg3:string,arg4:string):Promise<deck.ListResult>;

export function ListAllUnique(arg1:string):Promise<deck.ListResult>;

export function Read(arg1:string,arg2:string,arg3:string):Promise<deck.Result>;

export function Update(arg1:string,arg2:string,arg3:string,arg4:catalog.WriteRequest):Promise<deck.Result>;
