// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {catalog} from '../models';
import {card} from '../models';

export function Create(arg1:string,arg2:string,arg3:string,arg4:catalog.WriteRequest):Promise<card.Result>;

export function Delete(arg1:string,arg2:string,arg3:string,arg4:number):Promise<void>;

export function List(arg1:string,arg2:string,arg3:string,arg4:string,arg5:string):Promise<card.ListResult>;

export function Read(arg1:string,arg2:string,arg3:string,arg4:number):Promise<card.Result>;

export function Update(arg1:string,arg2:string,arg3:string,arg4:number,arg5:catalog.WriteRequest):Promise<card.Result>;
