// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Create(arg1, arg2, arg3, arg4) {
  return window['go']['card']['Card']['Create'](arg1, arg2, arg3, arg4);
}

export function Delete(arg1, arg2, arg3, arg4) {
  return window['go']['card']['Card']['Delete'](arg1, arg2, arg3, arg4);
}

export function List(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['card']['Card']['List'](arg1, arg2, arg3, arg4, arg5);
}

export function Read(arg1, arg2, arg3, arg4) {
  return window['go']['card']['Card']['Read'](arg1, arg2, arg3, arg4);
}

export function Update(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['card']['Card']['Update'](arg1, arg2, arg3, arg4, arg5);
}
