// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function CreateGame(arg1:main.CreateGameRequest):Promise<main.GameResult>;

export function DeleteGame(arg1:string):Promise<void>;

export function DuplicateGame(arg1:string,arg2:string):Promise<main.GameResult>;

export function ListGames(arg1:string,arg2:string):Promise<main.ListGamesResult>;

export function ReadGame(arg1:string):Promise<main.GameResult>;

export function UpdateGame(arg1:string,arg2:main.CreateGameRequest):Promise<main.GameResult>;
