// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CreateCollection(arg1, arg2) {
  return window['go']['main']['App']['CreateCollection'](arg1, arg2);
}

export function CreateGame(arg1) {
  return window['go']['main']['App']['CreateGame'](arg1);
}

export function DeleteCollection(arg1, arg2) {
  return window['go']['main']['App']['DeleteCollection'](arg1, arg2);
}

export function DeleteGame(arg1) {
  return window['go']['main']['App']['DeleteGame'](arg1);
}

export function DuplicateGame(arg1, arg2) {
  return window['go']['main']['App']['DuplicateGame'](arg1, arg2);
}

export function ListCollections(arg1, arg2, arg3) {
  return window['go']['main']['App']['ListCollections'](arg1, arg2, arg3);
}

export function ListGames(arg1, arg2) {
  return window['go']['main']['App']['ListGames'](arg1, arg2);
}

export function ReadCollection(arg1, arg2) {
  return window['go']['main']['App']['ReadCollection'](arg1, arg2);
}

export function ReadGame(arg1) {
  return window['go']['main']['App']['ReadGame'](arg1);
}

export function UpdateCollection(arg1, arg2, arg3) {
  return window['go']['main']['App']['UpdateCollection'](arg1, arg2, arg3);
}

export function UpdateGame(arg1, arg2) {
  return window['go']['main']['App']['UpdateGame'](arg1, arg2);
}
