// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CreateGame(arg1) {
  return window['go']['main']['App']['CreateGame'](arg1);
}

export function DeleteGame(arg1) {
  return window['go']['main']['App']['DeleteGame'](arg1);
}

export function DuplicateGame(arg1, arg2) {
  return window['go']['main']['App']['DuplicateGame'](arg1, arg2);
}

export function ListGames(arg1, arg2) {
  return window['go']['main']['App']['ListGames'](arg1, arg2);
}

export function ReadGame(arg1) {
  return window['go']['main']['App']['ReadGame'](arg1);
}

export function UpdateGame(arg1, arg2) {
  return window['go']['main']['App']['UpdateGame'](arg1, arg2);
}
